# Generated by Django 4.0.3 on 2022-03-11 11:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
