# Generated by Django 4.0.2 on 2022-03-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todo_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
